# Generated by Django 3.1.5 on 2022-01-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='massage',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='isim_soyisim',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
