# Generated by Django 3.1.5 on 2022-01-24 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adı', models.CharField(help_text='Ürün Adını Giriniz', max_length=200, verbose_name='Ürün Adı')),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('resim', models.ImageField(upload_to='urunler/%Y/%m/%d')),
                ('tarih', models.DateField(auto_now=True)),
                ('fiyat', models.CharField(max_length=200)),
                ('indirimli_fiyat', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=True)),
                ('facebook', models.URLField(blank=True, max_length=100)),
                ('twitter', models.URLField(blank=True, max_length=100)),
                ('youtube', models.URLField(blank=True, max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='urunler.category')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='urunler.Tag')),
            ],
        ),
    ]
