# Generated by Django 3.2.8 on 2022-01-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='resim_bir',
            field=models.ImageField(default=2, upload_to='urunler/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urunler',
            name='resim_iki',
            field=models.ImageField(default=2, upload_to='urunler/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urunler',
            name='resimm_uc',
            field=models.ImageField(default=2, upload_to='urunler/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
